### ISSUE TITLE
Electronic Contract Administration System - Implementation

### ISSUE THREAD

**Issue by bcdevex** [bcgov/EDUC-ECAS#17]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-electronic-contract-administration-system---implementation"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-electronic-contract-administration-system---implementation">visit the opportunity page</a>.
The opportunity closes on <b>Monday, August 26th, 2019 at 16:00 PDT</b>.</p>

**Comment by asparker72** [comment]
We have the following clarification related to this opportunity (Electronic Contract Administration System - Implementation):
1.	The current version of Microsoft Dynamics
2.	Is this requirement is for onsite model or client is fine to execute this project in  onsite/offshore model
3.	We are assuming that Technical documentation available for already customized modules
4.	SQL and clustering details (if the customer has done SQL clustering with SQL version details)
5.	Details about 3rd party software/hardware integrations if any and how these are integrated (API, XML, etc.)
6.	Any mobile/ Tab compatibility
7.	We are assuming that there is no need for functional consultant and customer need technical consultant
8.	We are assuming that the customer will do production deployment.
9.	Number of user licenses

**Comment by bcdevex** [comment]
This opportunity has been assigned
