### ISSUE TITLE
ECAS Interface completion.

### ISSUE THREAD

**Issue by bcdevex** [bcgov/EDUC-ECAS#23]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-corporate-accounting-system-supplier-interface"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-corporate-accounting-system-supplier-interface">visit the opportunity page</a>.
The opportunity closes on <b>Friday, February 14th, 2020 at 16:00 PST</b>.</p>

**Comment by richkallan** [comment]
Acceptance Criteria 4 says "...and utilize the sequences on the tables above." Can you provide more information about the sequence number. Is this one that is provided by Dynamics or by T4A. If it's created and provided by T4A how is it currently used by ECAS. I.E. how is ECAS aware of which T4A sequence numbers are required by ECAS?

**Comment by richkallan** [comment]
s the proposed approach expected to be that development is done directly against the MS SQL server hosting the Dynamics data? This is asked because of the following statements...

Acceptance Criteria #5 - Create views or procedures in MS SQL to access Oracle T4A tables from the MS SQL server for:

 

AND 

"To assist you in all of this work, our DBAs will:

- Install Oracle Client on MS SQL servers and configure them to speak to ECAS/T4A Oracle. (This is already completed in our Dev environment.)

**Comment by GregFPoirier** [comment]
Thanks for the Questions Rich:

1) the current ECAS system uses the sequences when a new supplier or a new location is created. IE (insert into exa_parties (prty_id) values (nextvalue.exa_prty_seq) 

The new Dynamics system will need to utilize that sequence number through the DB Link.  
similar to 
declare @v_prty_id integer;
select @v_prty_id=sequence_prty from openquery(ecas_oracle,'select exa_prty_seq.nextval sequence_prty from dual')

We have a list of the sequences that need to be used for this process and access to the environment.

2) Yes, that is the most promising option but if it can be done directly from Dynamics then we could discuss.  Ultimately is we need to utilize procedures and tables in an Oracle database.

**Comment by GregFPoirier** [comment]
For all that are responding to the Code with Us.  Note that the opportunity states 4 two week sprints.  However, once accepted will only 6.5 weeks for this project to complete this fiscal.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by GregFPoirier** [comment]
Thank you to everyone that responded to this opportunity.  Based on the evaluation criteria,  @richkallan and team scored the highest, so we are assigning him to work on this issue.
